name: ieqa
dependencies:
- flask=0.10.1=py27_1
- freetype=2.5.2=2
- ipython=3.1.0=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_2
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.1=np19py27_0
- pip=7.0.1=py27_0
- pyparsing=2.0.3=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_3
- pytz=2015.4=py27_0
- readline=6.2=2
- setuptools=17.0=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- xlrd=0.9.3=py27_0
- zlib=1.2.8=0
- pip:
  - alembic==0.7.6
  - blinker==1.3
  - coverage==3.7.1
  - flask-admin==1.1.0
  - flask-bootstrap==3.3.2.1
  - flask-login==0.2.11
  - flask-mail==0.9.1
  - flask-migrate==1.4.0
  - flask-pymongo==0.3.1
  - flask-script==2.0.5
  - flask-sqlalchemy==2.0
  - flask-wtf==0.11
  - mako==1.0.1
  - pymongo==2.7.2
  - selenium==2.45.0
  - sqlalchemy==1.0.3
  - wtforms==2.0.2

