name: ieqa
dependencies:
- flask=0.10.1=py27_1
- ipython=3.1.0=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- markupsafe=0.23=py27_0
- openssl=1.0.1k=1
- pip=6.1.1=py27_0
- python=2.7.9=1
- python.app=1.2=py27_3
- readline=6.2=2
- setuptools=15.2=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- zlib=1.2.8=0
- pip:
  - alembic==0.7.6
  - blinker==1.3
  - coverage==3.7.1
  - flask-bootstrap==3.3.2.1
  - flask-login==0.2.11
  - flask-mail==0.9.1
  - flask-migrate==1.4.0
  - flask-script==2.0.5
  - flask-sqlalchemy==2.0
  - flask-wtf==0.11
  - mako==1.0.1
  - selenium==2.45.0
  - sqlalchemy==1.0.3
  - wtforms==2.0.2

